core/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [
    path(
        'index/',
        views.index,
        name='index'),

    path(
        'gallery/',
        views.gallery,
        name='gallery'),

    path(
        'feedbackandcontacts/',
        views.feedbackandcontacts,
        name='feedbackandcontacts'),

    path(
        'menu-product/',
        views.menu,
        name='menu-product'),

    path(
        'order/', 
        views.order, 
        name='order'),

    path(
        'online-order/',
        views.order,
        name='online_order'),

    path(
        'reservation/',
        views.reservation,
        name='reservation'),

    path(
        'specialoffers/',
        views.specialoffers,
        name='specialoffers'),

    path(
        'create_payment/', 
        views.create_payment, 
        name='create_payment'),

    path(
        'confrim_payment/', 
        views.confirm_payment, 
        name='confirm_payment'),
]

core/main_app/models.py
from django.db import models

# Create your models here.

class FeedBack(models.Model):
    name = models.CharField(max_length=50, verbose_name='Ваше имя')
    email = models.EmailField(verbose_name='Ваш email')
    description = models.TextField(verbose_name='')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Обратный отзыв'
        verbose_name_plural = 'Обратные отзывы'

    def __str__(self) -> str:
        return self.name

class AboutRestaurant(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название ресторана')
    address = models.CharField(max_length=100, verbose_name='Адрес')
    phone_number = models.CharField(max_length=30, verbose_name='Номер телефона')
    work_hours = models.TextField(verbose_name='Режим работы')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'О нас'
        verbose_name_plural = 'О нас'

    def __str__(self) -> str:
        return self.name

class PhotoGallery(models.Model):
    image = models.ImageField(verbose_name='Фотография', upload_to='media/%Y/%M/%D')

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

class News(models.Model):
    name = models.CharField(max_length=150, verbose_name='Новости')
    description = models.TextField(verbose_name='Описание')
    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(verbose_name='Конец акции')

    class Meta:
        verbose_name='Новость'
        verbose_name_plural='Новости'

    def __str__(self) -> str:
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Категория')

    class Meta:
        verbose_name='Категория'
        verbose_name_plural='Категории'

    def __str__(self) -> str:
        return self.name

class Menu(models.Model):
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name='Наименование блюда')
    image = models.ImageField(verbose_name='Изображение', upload_to=('menu_images/%Y/%M/%D'))
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=15000, decimal_places=3, verbose_name='Цена')
    
    class Meta:
        verbose_name='Блюдо'
        verbose_name_plural='Блюда'

    def __str__(self) -> str:
        return self.name

class Feed_Back(models.Model):  #отзывы
    title = models.CharField(max_length=200, verbose_name='Оглавление')
    description = models.TextField(verbose_name='Описание')
    username = models.CharField(max_length=20, verbose_name='Ваше имя', blank=True)
    phone_number = models.CharField(max_length=30, verbose_name='Номер телефона', blank=True)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

    def __str__(self) -> str:
        return self.title

class PaymentInfo(models.Model):
    name = models.CharField(max_length=30, verbose_name='Оплата')
    description = models.TextField(verbose_name='Описание оплаты')

    class Meta:
        verbose_name = 'Оплата'
        verbose_name_plural = 'Оплаты'

    def __str__(self) -> str:
        return self.name

class Booking(models.Model):
    name = models.CharField(max_length=50, verbose_name='Ваше имя')
    email = models.EmailField(verbose_name='email')
    phone_number = models.CharField(max_length=40, verbose_name='Номер телефона')
    date = models.DateField(verbose_name='Дата')
    num_guests = models.IntegerField(verbose_name='Количество гостей')

    class Meta:
        verbose_name = 'Бронь'
        verbose_name_plural = 'Брони'

    def __str__(self) -> str:
        return self.name

core/main_app/views.py
from django.shortcuts import render

# Create your views here.

core/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Aksaray Grand Hall | Home</title>
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/aksaraylogo.ico' %}" type="image/x-icon">

    <!-- Font awesome -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!-- Slick slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <!-- Date Picker -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.css' %}">
     <!-- Gallery Lightbox -->
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
    <!-- Theme color -->
    <link id="switcher" href="{% static 'css/theme-color/default-theme.css' %}" rel="stylesheet">

    <!-- Main style sheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">


    <!-- Google Fonts -->

    <!-- Prata for body  -->
    <link href='https://fonts.googleapis.com/css?family=Prata' rel='stylesheet' type='text/css'>
    <!-- Tangerine for small title -->
    <link href='https://fonts.googleapis.com/css?family=Tangerine' rel='stylesheet' type='text/css'>
    <!-- Open Sans for title -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>



    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>

  <!--START SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#">
      <i class="fa fa-angle-up"></i>
    </a>
  <!-- END SCROLL TOP BUTTON -->

  <!-- Start header section -->
  <header id="mu-header">
    <nav class="navbar navbar-default mu-main-navbar" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- LOGO -->

           <!--  Text based logo  -->
          <a class="navbar-brand" href="{% url 'main_app:index' %}">Aksaray<span>GrandHall</span></a>

		      <!--  Image based logo  -->
<!--           <a class="navbar-brand" href="index.html"><img src="{% static 'img/aksaraylogo.jpg' %}" alt="Logo img"></a>-->


        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="top-menu" class="nav navbar-nav navbar-right mu-main-nav">
           <li><a href="{% url 'main_app:index' %}">ГЛАВНАЯ</a></li>
           <li><a href="{% url 'main_app:menu-product' %}">МЕНЮ</a></li>
           <li><a href="{% url 'main_app:gallery' %}">ГАЛЕРЕЯ</a></li>
           <li><a href="{% url 'main_app:reservation' %}">БРОНИРОВАНИЕ</a></li>
<!--            <li><a href="mu-client-testimonial">ОТЗЫВЫ</a></li>-->
            <li><a href="{% url 'main_app:specialoffers' %}">АКЦИИ</a></li>
            <li><a href="{% url 'main_app:feedbackandcontacts' %}">ОБРАТНАЯ СВЯЗЬ & КОНТАКТЫ</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  </header>
  <!-- End header section -->

  {% block content %}

  {% endblock %}

   <!-- Start Contact section -->

   <section id="mu-contact">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="mu-contact-area">

            <div class="mu-title">
              <span class="mu-subtitle">Связаться С Нами</span>
            </div>

            <div class="mu-contact-content">
              <div class="row">

                <div class="col-md-6">
                  <div class="mu-contact-left">
                    <!-- Email message div -->
                    <div id="form-messages"></div>
                    <!-- Start contact form -->
                    <form id="ajax-contact" method="post" action="mailer.php" class="mu-contact-form">
                      <div class="form-group">
                        <label for="name">Ваше Имя</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Имя" required>
                      </div>
                      <div class="form-group">
                        <label for="email">Aдрес Электронной Почты</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                      </div>
                      <div class="form-group">
                        <label for="subject">Тема</label>
                        <input type="text" class="form-control" id="subject" name="subject" placeholder="Тема" required>
                      </div>
                      <div class="form-group">
                        <label for="message">Сообщение</label>
                        <textarea class="form-control" id="message" name="message"  cols="30" rows="10" placeholder="Введите Свое Сообщение" required></textarea>
                      </div>
                      <button type="submit" class="mu-send-btn">Отправить Сообщение</button>
                    </form>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="mu-contact-right">
                    <div class="mu-contact-widget">
                      <h3>Наш Адрес</h3>
                      <p>Удобная локация с просторной парковкой. Свежий горный воздух и большая уличная терраса для бесед и отдыха.</p>
                      <address>
                        <p><i class="fa fa-phone"></i> 0501 10 30 20 </p>
<!--                        <p><i class="fa fa-envelope-o"></i>contact@markups.io</p>-->
                        <p><i class="fa fa-map-marker"></i>Улица Анкара 7/2, Бишкек</p>
                      </address>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Contact section -->

  <!-- Start Map section -->
  <section id="mu-map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d9207.358598888495!2d-85.64847801496286!3d30.183918972289003!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x2320479d70eb6202!2sDillard&#39;s!5e0!3m2!1sbn!2sbd!4v1462359735720" width="100%" height="100%" frameborder="0"
            allowfullscreen></iframe>
  </section>
  <!-- End Map section -->

   <!-- Start Footer -->
   <footer id="mu-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <div class="mu-footer-area">
           <div class="mu-footer-social">
            <a href="https://www.instagram.com/aksaray_grandhall/"><span class="fa fa-instagram"></span></a>
          </div>
          <div class="mu-footer-copyright">
            <p>&copy; Copyright <a rel="nofollow" href="http://markups.io">markups.io</a>. All right reserved.</p>
          </div>
        </div>
      </div>
      </div>
    </div>
  </footer>
  <!-- End Footer -->

  <!-- jQuery library -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <!-- Slick slider -->
  <script type="text/javascript" src="{% static 'js/slick.js' %}"></script>
  <!-- Counter -->
  <script type="text/javascript" src="{% static 'js/simple-animated-counter.js' %}"></script>
  <!-- Gallery Lightbox -->
  <script type="text/javascript" src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <!-- Date Picker -->
  <script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <!-- Ajax contact form  -->
  <script type="text/javascript" src="{% static 'js/app.js' %}"></script>

  <!-- Custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
      </div>
    </div>
  </section>
  </body>
</html>